// src/routes/index.js
const express = require('express');
const { body, param } = require('express-validator');
const productController = require('../controllers/productController');
const reservationController = require('../controllers/reservationController');
const checkoutController = require('../controllers/checkoutController');

const router = express.Router();

/* Product routes */
router.post(
  '/products',
  body('sku').isString().notEmpty(),
  body('name').isString().notEmpty(),
  body('total_stock').isInt({ min: 0 }),
  productController.createProduct
);

// product id is a Mongo ObjectId
router.get(
  '/products/:id/status',
  param('id').isMongoId(),
  productController.getStatus
);

/* Reservation routes */
// single reserve: productId must be a Mongo ObjectId
router.post(
  '/reserve',
  body('userId').isString().notEmpty(),
  body('productId').isMongoId(),
  body('qty').isInt({ min: 1 }),
  reservationController.reserveSingle
);

// reserve multiple: validate array and each item's productId & qty
router.post(
  '/reserve-multiple',
  body('userId').isString().notEmpty(),
  body('items').isArray({ min: 1 }),
  body('items.*.productId').isMongoId(),
  body('items.*.qty').isInt({ min: 1 }),
  reservationController.reserveMultiple
);

// list reservations for a user (userId is free-form string)
router.get(
  '/user/:userId/reservations',
  param('userId').isString().notEmpty(),
  reservationController.getUserReservations
);

// cancel reservation: reservation id is UUID generated by the app
router.post(
  '/reservation/:id/cancel',
  param('id').isUUID(),
  body('userId').isString().notEmpty(),
  reservationController.cancelReservation
);

/* Checkout */
// reservationId in body must be the UUID returned by reserve endpoint
router.post(
  '/checkout',
  body('userId').isString().notEmpty(),
  body('reservationId').isUUID(),
  checkoutController.checkout
);

module.exports = router;
